### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by ChandraLingam** [arogozhnikov/arogozhnikov.github.io#10]
Thank you for a great post on comparison of different Factorization Machine implementations.

I have a very basic query; Is factorization machine designed to work only with binary fields?  Do we need to one hot encode all features?  How are real-valued featured handled?

Thank you!

**Comment by arogozhnikov** [comment]
Hi, 

> I have a very basic query; Is factorization machine designed to work only with binary fields? 

No, it is possible to handle real-valued variables

> Do we need to one hot encode all features? 

As for categorical features, that's the most sane and common option.

> How are real-valued featured handled?

You'd better read original paper, those participate as multipliers. FM is no more than a second-order polynomial with respect to features, but coefficients are computed via a smart formula.

Here is a paper https://www.csie.ntu.edu.tw/~b97053/paper/Rendle2010FM.pdf

**Comment by ChandraLingam** [comment]
Thank you so much.
