### ISSUE TITLE
Tips and Tricks 2 Bug

### ISSUE THREAD

**Issue by seanlaw** [arogozhnikov/arogozhnikov.github.io#5]
In notebooks/2015-09-30-NumpyTipsAndTricks2.ipynb,

    def running_average_simple(seq, window=100):
        result = np.zeros(len(seq) - window)  # The bug is in this line
        for i in range(len(result)):
            result[i] = np.mean(seq[i:i + window])
        return result

Should be

    def running_average_simple(seq, window=100):
        result = np.zeros(len(seq) - window + 1)  # Fixed off by one bug
        for i in range(len(result)):
            result[i] = np.mean(seq[i:i + window])
        return result

**Comment by arogozhnikov** [comment]
Fixed this, thanks for the report!
