### ISSUE TITLE
Не работает визуализация градиентного бустинга.

### ISSUE THREAD

**Issue by MichaelMonashev** [arogozhnikov/arogozhnikov.github.io#6]
На странице http://arogozhnikov.github.io/2016/06/24/gradient_boosting_explained.html в Хроме пишет, что "Webgl is not supported by your browser - visit http://get.webgl.org for more info". Но зайдя на http://get.webgl.org я вижу вращающийся куб и написано: "Your browser supports WebGL", т.е. он всё таки работает.

В консоле браузера выводится следующая ошибка:
```
plotly-1.13.js:77919 Uncaught TypeError: Cannot read property 'canvas' of undefined
initializeGLPlot@ plotly-1.13.js:77919
Scene @ plotly-1.13.js:78005
plotGl3d @ plotly-1.13.js:76899
drawData @ plotly-1.13.js:63735
lib.syncOrAsync @ plotly-1.13.js:61329
Plotly.plot @ plotly-1.13.js:63772
Plotly.newPlot @ plotly-1.13.js:64297
DecisionTreeVisualization @ gradient_boosting_explained.js:143
(anonymous function) @ gradient_boosting_explained.js:175
```

Видимо или ошибка в plotly или в том, как его используют.

**Comment by arogozhnikov** [comment]
No idea. Демке уже больше года, в хромах раньше точно работала.
- хромиум 60 ok
- Я.Браузер 17.6 ok

Возможная причина - plotly не признает наличие webgl на многих мобильных устройствах.

**Comment by MichaelMonashev** [comment]
Да, ты прав. Проблема в Plot.ly . Тут https://plot.ly/javascript/3d-scatter-plots/ вывелась та же ошибка.

**Comment by MichaelMonashev** [comment]
проблема решилась настройками Хрома https://github.com/plotly/plotly.js/issues/1992

**Comment by MichaelMonashev** [comment]
Спасибо за визуализацию. С ней лучше понимаешь отличие дерева решений от леса деревьев.

**Comment by arogozhnikov** [comment]
You're welcome. Всегда пожалуйста :)
