### ISSUE TITLE
some question about Learning to rank (software, datasets)

### ISSUE THREAD

**Issue by cuixue** [arogozhnikov/arogozhnikov.github.io#7]
hi,  happy to read your post "Learning to rank (software, datasets)"
In this post , you say the text of query and document are available of MSLR-WEB10k and MSLR-WEB30k, 
 
However, I couldn't find the text using this download link https://www.microsoft.com/en-us/research/project/mslr/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fprojects%2Fmslr%2Fdownload.aspx. 

Could you help me to tell the accurate download link.

Thank you!

**Comment by arogozhnikov** [comment]
I've used only numerical features but previously was sure that title and query are available.
According to http://arxiv.org/abs/1306.2597, those are not provided, so there is a mistake in the post, sorry
