### ISSUE TITLE
how reproduce great code 2016-02-15-TestingLibFM.ipynb ?

### ISSUE THREAD

**Issue by Sandy4321** [arogozhnikov/arogozhnikov.github.io#9]
may you share function load_problems
so this line will not give error
import load_problems
then it it will be possible to reproduce results
thanks
by the way , what you think why logistic regression is so good
actually there is no need in FM??

**Comment by arogozhnikov** [comment]
I think you need this one

https://github.com/arogozhnikov/cats/blob/master/notebooks/load_problems.py


All the related code is also in that repository, however you'll need first to download datasets and then call prepare function(s) to prepare datasets
